version: "3"
   
services:
  db:
    image: postgres:13.2
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${WEB_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  web:
    image: aimerfan/flowlab
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/flowlab
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: