# Generated by Django 3.2.6 on 2021-12-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211208_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='實驗名稱')),
                ('branch', models.CharField(max_length=72, verbose_name='繳交分支')),
                ('description', models.TextField(blank=True, verbose_name='實驗描述')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='繳交期限')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='關聯課程')),
            ],
            options={
                'verbose_name': '實驗',
                'verbose_name_plural': '實驗',
                'unique_together': {('course', 'name')},
            },
        ),
    ]
