# Generated by Django 3.2.10 on 2022-01-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_remove_project_labs'),
        ('course', '0005_lab_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.template', verbose_name='套用模板'),
        ),
    ]
