# Generated by Django 3.2.10 on 2022-02-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0006_lab_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', '問答題'), ('single', '單選題'), ('multiple', '多選題')], max_length=50, verbose_name='題目類型')),
                ('content', models.CharField(max_length=256, verbose_name='題目內容')),
                ('number', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='編號')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lab', verbose_name='實驗')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
                'unique_together': {('lab', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='選項內容')),
                ('number', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='編號')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question', verbose_name='題目')),
            ],
            options={
                'verbose_name': '選項',
                'verbose_name_plural': '選項',
                'unique_together': {('topic', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='答案')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='學生')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question', verbose_name='題目')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
                'unique_together': {('content',)},
            },
        ),
    ]
