# Generated by Django 3.2.6 on 2021-12-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211208_0330'),
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='關聯課程'),
        ),
    ]
