# Generated by Django 3.2.10 on 2021-12-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_students'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.AddField(
            model_name='project',
            name='labs',
            field=models.ManyToManyField(blank=True, to='course.Lab'),
        ),
    ]
