# Generated by Django 3.2.10 on 2022-01-17 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import flow.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flow', '0002_auto_20211214_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模板名稱')),
                ('template', models.FileField(upload_to=flow.models.upload_to_path, verbose_name='模板檔案')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='建立日期')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'unique_together': {('teacher', 'name')},
            },
        ),
    ]
