# Generated by Django 3.2.10 on 2022-01-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='labs',
        ),
    ]
